### ISSUE TITLE
Update Lock Mechanism of Outside Storage Box

### ISSUE THREAD

**Issue by Dijapirzada** [United-Home/200-Henrietta#8]
- Space: Our lock of outside storage box was broken and our landscaping equipment was stolen. 

We have a rubber latch right now. Pictures below show it. And we want to update it to Metal latch.

![image](https://user-images.githubusercontent.com/117278179/208711849-9db2d098-8e72-4778-bcda-fee8007fb9b7.png)
![image](https://user-images.githubusercontent.com/117278179/208711940-b59e1444-fcfb-494a-8dde-a64546aec7fa.png)
![image](https://user-images.githubusercontent.com/117278179/208712022-d76359d5-49e6-49cf-9148-e23b07c26ff7.png)
Update it to this
![image](https://user-images.githubusercontent.com/117278179/208713024-93ce1811-a6df-4c69-834a-1d1f09778b71.png)

**Comment by SuzyQuant** [comment]
This is updated to a keyless lock system.
